use_frameworks!
platform :ios, '8.0'

target 'NumberSpellOutFormatter_Example' do
  pod 'NumberSpellOutFormatter', :path => '../'
  inhibit_all_warnings!

  target 'NumberSpellOutFormatter_Tests' do
    inherit! :search_paths
  end
end
